import type { Metadata } from "next";
import StoreProvider from "@/store/StoreProvider";
import Header from "@/components/Header";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body>
          <Header/>
          <main> {children}</main>
        </body>
      </StoreProvider>
    </html>
  );
}
