import type { Metadata } from "next";
import StoreProvider from "@/store/StoreProvider";
import Header from "@/components/Header";
import "./globals.scss";
import ThemeProvider from "@/assets/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <ThemeProvider>
          <body>
            <Header />
            <main> {children}</main>
          </body>
        </ThemeProvider>
      </StoreProvider>
    </html>
  );
}
